[package]
name = "memish"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]

[dependencies]

[dependencies.bevy]
version = "0.12.0"
# default-features = false
features = []
